### ISSUE TITLE
dpd.js is not generating login function and me function

### ISSUE THREAD

**Issue by amitsang2000** [deployd/deployd#796] opened 2017-01-11 14:43 UTC
dpd.js is not generating login function and me function.
Link to dpd.js 
[http://konnect.asia:5000/dpd.js](http://konnect.asia:5000/dpd.js)
It is suggested not to use dpd.js in production, then what should I use.
If I want to use dpd.js for my testing purpose then how to resolve the issue I mentioned above.

**Comment by rgolea** [comment] 2017-01-11 14:49
The problem is that your users collection is not a type users collection. It's just a collection. I know that because your password is revealed. You have to specify it's a collection of type users when you're adding the collection.
![screen shot 2017-01-11 at 15 47 06](https://cloud.githubusercontent.com/assets/8843202/21852944/58209378-d815-11e6-926f-e0ec42efca8b.png)

If you're using angular use $resource, $http, angular-dpd (by @andreialecu ), even jquery.

**Comment by rgolea** [comment] 2017-01-11 14:49
I'm closing this because it's not really an issue. It's a user mistake.

**Closed by rgolea** 2017-01-11 14:49 UTC

**Comment by amitsang2000** [comment] 2017-01-11 15:16
@rgolea  Thanks a lot !!! for showing me the right path and for your help.

**Comment by rgolea** [comment] 2017-01-11 15:17
@amitsang2000 any time!

**Comment by amitsang2000** [comment] 2017-01-21 14:22
Hi,
Can you please help me with the following:
Is there anyway to change or replace the id generated by deployd.
where these id get stored?

**Comment by amitsang2000** [comment] 2017-01-21 14:40
![image](https://cloud.githubusercontent.com/assets/4608036/22175152/7d994980-e015-11e6-99f5-679a329e13af.png)

if i do inspect element it shows bad request 400.
but i can open it on browser
[http://konnect.asia:5000/users/6aea7d9ed7893869](http://konnect.asia:5000/users/6aea7d9ed7893869)
