### ISSUE TITLE
Booleans always save as false.

### ISSUE THREAD

**Issue by iantearle** [deployd/deployd#166] opened 2013-03-19 10:53 UTC
I have a collection that no matter how I submit as true, even the API example booleans save as false.

**Comment by NicolasRitouet** [comment] 2015-02-13 16:37
True, I can reproduce the issue.
I'll have to investigate a bit more, but it could come from this line:
https://github.com/deployd/deployd/blob/077c2b97cffee6c14f4f10391c3f78b7055aae8d/lib/resources/collection/index.js#L89

**Comment by NicolasRitouet** [comment] 2015-02-13 22:34
Ok, I found the issue, it's really weird that nobody noticed that before.
boolean were always set to false ...

Fixed with #512

**Comment by petergoes** [comment] 2015-02-15 14:15
Thank you!

**Comment by andreialecu** [comment] 2015-02-24 11:15
@petergoes we need more information on this, can you share your config.json from the resource? The #512 fix is actually not a fix for this problem, and I personally cannot reproduce this.

**Comment by lapak10** [comment] 2015-06-30 08:34
the problem is still there.... (v 0.8.4)

**Comment by andreialecu** [comment] 2015-06-30 13:03
Could never reproduce this. Make sure you're sending valid json.

If you can show a way to reproduce this, let me know and I'll look into it.

**Comment by petergoes** [comment] 2015-06-30 23:16
First of all, I am sorry for my late response. It has been a wile since I worked with Deployd so I had to do some digging. The issue still remains for me on v0.8.4 as well. 

My `config.json`:
```
{
	"type": "Collection",
	"properties": {
		"myName": {
			"name": "myName",
			"type": "string",
			"typeLabel": "string",
			"required": false,
			"id": "myName",
			"order": 0
		},
		"myBoolean": {
			"name": "myBoolean",
			"type": "boolean",
			"typeLabel": "boolean",
			"required": false,
			"id": "myBoolean",
			"order": 1
		}
	}
}
```

Second, the response of a postman request (notice the `true` value of myBoolean in for form and the `false` value of `myBoolean` in the response):
![screen shot 2015-07-01 at 00 51 17](https://cloud.githubusercontent.com/assets/642489/8443926/6119aea4-1f8b-11e5-94ee-80efd972edb8.png)

I did some digging through the source code, by searching for `is required`, and I found this line: 
https://github.com/deployd/deployd/blob/master/lib/resources/collection/index.js#L89
I don't have real good understanding of the code, but it seems to me that the method `Collection.prototype.validate()` is validating the input it gets from a POST request. I noticed a couple of things:
* The `myBoolean` is required -> `myBoolean` is `false` -> error: `"myBoolean": "is required"` = A new record despite the error.
* The `myBoolean` is required -> `myBoolean` is `true` -> error: `"myBoolean": "is required"` = no new record
* The `myBoolean` is *NOT* required -> `myBoolean` is `true` -> No error = new record with `myBoolean` value of `false` (This is the main issue of this thread)
* __These issues only happen when the post is being done via a HTTP request! When the JavaScript command: `dpd.myobjects.post({myName:"PostViaJavaScript", myBoolean:true})` is executed on `localhost:2403` everything works as expected!!__

@andreialecu I hope you can do something with the info I provided.

**Comment by andreialecu** [comment] 2015-06-30 23:42
Ah I see what might be going on now.

Try posting JSON data instead of x-www-form-urlencoded. I don't think that is fully supported.

**Comment by petergoes** [comment] 2015-07-01 07:48
So something like this will never work?
```
<form method="post" action="http://localhost:2403/my-objects">
    <input type="text" name="myName" />
    <input type="checkbox" name="myBoolean" />
    <input type="submit" value="submit" />
</form>
```

**Comment by andreialecu** [comment] 2015-07-01 09:54
It can probably be made to work, but it's not a documented use case of deployd. Once you step outside of the documentation, results can be unexpected.

See:
http://docs.deployd.com/docs/collections/reference/http.html

**Comment by lapak10** [comment] 2015-07-01 10:38
400-bad request when POST-ing new comment (with content-type json)...

jQuery.ajax({
        'type': 'POST',
        'url':'http://localhost:2403/comments',
        'contentType': 'application/json',
        'data': JSON.stringify({comment:'just a sample comment',like:false})
    });

GIVEN: comments is a collection with comment as string property and like as boolean required.

**Comment by andreialecu** [comment] 2015-07-04 16:22
This is a jQuery question now, the proper syntax would be more like this:

```javascript
   $.ajax({
      type: "POST",
      contentType: "application/json",
      url: 'http://localhost:2403/comments',
      data: {comment: 'just a sample comment', like:false},
      dataType: "json"
   });
```

**Closed by andreialecu** 2015-07-04 16:22 UTC
Labels: type: bug
