### ISSUE TITLE
Notifying specific clients realtime

### ISSUE THREAD

**Issue by kkrishnan90** [deployd/deployd#779] opened 2016-10-29 11:36 UTC
Using deployd socket API , is there any way I can notify or emit only to specific clients ? I have seen the documentation but it's more of like broadcasting to everyone ..  I am creating a private chat app on android using deployd as a backend .. any help on this issue would be appreciated! Thanks in advance !

**Comment by andreialecu** [comment] 2016-10-29 11:40
Yes, see documentation here:
http://docs.deployd.com/docs/collections/reference/#s-emit()-764

Also, there is a (yet) undocumented feature here: https://github.com/deployd/deployd/pull/698#issuecomment-166901474

**Comment by kkrishnan90** [comment] 2016-10-29 11:43
So according to the undocumented feature as suggested by you ,

emit('administrators', 'eventname', { ... });

Instead of administrator the username should be replaced there .. please do correct me if I'm wrong.

**Comment by andreialecu** [comment] 2016-10-29 11:45
As long as you call `session.joinChannel(username)` in `On Login`, yes.

**Comment by kkrishnan90** [comment] 2016-10-29 11:49
Ok great I'll try this now and will comment here in a short while ! Thank you for your immediate response mate !

**Comment by kkrishnan90** [comment] 2016-10-29 12:00
This is what I get when I put that code in OnLogin 

{
  "message": "session.joinChannel is not a function",
  "status": 400
}

Anything to be done apart from what you've suggested ?

**Comment by andreialecu** [comment] 2016-10-29 12:04
What version of deployd are you running? That code has been in the core since 2015, so that's a weird error.

**Comment by kkrishnan90** [comment] 2016-10-29 12:05
krishmac:~ krish$ dpd -V
0.8.9
krishmac:~ krish$

**Comment by andreialecu** [comment] 2016-10-29 12:05
Oh, oops, it's joinRoom not joinChannel, see the comment I linked.

**Comment by kkrishnan90** [comment] 2016-10-29 12:07
Oops ! Sorry even I didn't notice that ! Sorry.. Im testing it now.. will update you in few mins.. Thanks again !

**Comment by kkrishnan90** [comment] 2016-10-30 07:32
Hi !
Sorry for the delayed response.. I tried yesterday with the linked comment code for joinRooms and the emit to specific user. I'm not able to get it to work. Could you please elaborate on the codes that you've used for joining room? I see a me.admin code but I'm not able to figure out what's happening when I change it to me.username .. Much appreciated if you provide me some snippets to connect it to a specific user. Thanks in advance!

**Comment by kkrishnan90** [comment] 2016-11-01 19:54
Any updates on this ?

**Comment by andreialecu** [comment] 2016-11-03 10:32
Not sure what your trouble is. As previously stated, what you need to do is call `session.joinRoom(...)` in the context of a session, like when a user logs in for example, or whenever else he calls some API method.

**Comment by andreialecu** [comment] 2016-11-05 17:36
Since this is not a bug, if you have further issues with this, please use gitter. I'm going to close this.

**Closed by andreialecu** 2016-11-05 17:36 UTC
