### ISSUE TITLE
command line error

### ISSUE THREAD

**Issue by lymanlai** [deployd/deployd#205] opened 2013-06-09 10:05 UTC
after I run dpd
then I am try to type something like "help"
then it turns out to be hheellpp
then I hit enter, it says command not found (of course...)

**Comment by NicolasRitouet** [comment] 2015-02-28 19:07
I can't reproduce this issue.
I'll close this ticket since it's really old.
If the problem still exists, feel free to reopen the ticket with additional details (OS, deployd version, nodejs version, etc...).

**Closed by NicolasRitouet** 2015-02-28 19:07 UTC
