### ISSUE TITLE
Recursion is defined wrong

### ISSUE THREAD

**Issue by bahadircyildiz** [deployd/deployd#788] opened 2016-12-21 08:50 UTC
Hello there,

I have a **course** table which has `instructorID` to retrieve data, and **userinfo** table that also has instructors itself. My main goal was getting instructor information by course's `get` API, so I prepared this sample.

### Courses / Events / on GET
```javascript
if(this.instructorID){
    dpd.userinfo.get({id: this.instructorID}).then(function(success){
        this.instructor = success;
    },function(err){
        this.instructor = err;
    })
}
```
### Output

```javascript
courses: 
[
      { title: 'Nesciunt esse blanditiis voluptatem quaerat magnam vero.',
        body: 'Reprehenderit qui eum ex ea dicta eligendi archite',
        price: 76,
        instructorID: 'd0cb61d7abe48b51',
        active: true,
        image: 'http://lorempixel.com/640/480/people',
        ribbon: [Object],
        hasRibbon: false,
        id: 'ed30c7fb198c9893',
        instructor: [Object] },
      { title: 'Non repudiandae est unde ex omnis dolor.',
        body: 'Libero maiores est et saepe beatae rerum molestiae',
        price: 74,
        instructorID: 'd0cb61d7abe48b51',
        active: true,
        image: 'http://lorempixel.com/640/480/transport',
        ribbon: [Object],
        hasRibbon: false,
        id: '7a3523b554b9585a',
        instructor: [Object] },
      { title: 'Possimus debitis est aut.',
        body: 'Atque temporibus et ea enim.',
        price: 60,
        instructorID: 'd0cb61d7abe48b51',
        active: true,
        image: 'http://lorempixel.com/640/480/business',
        ribbon: [Object],
        hasRibbon: false,
        id: '3627957964002b50',
        instructor: 'Recursive call to GET /userinfo detected' },
      { title: 'Sint voluptas dolor et architecto omnis repellat.',
        body: 'Error quasi dolor animi corporis quia consequatur ',
        price: 28,
        instructorID: 'd0cb61d7abe48b51',
        active: true,
        image: 'http://lorempixel.com/640/480/abstract',
        ribbon: [Object],
        hasRibbon: false,
        id: 'df4e057eea0c5851',
        instructor: 'Recursive call to GET /userinfo detected' },
      { title: 'Labore dicta dolores autem earum corporis nulla est dolores doloribus.',
       body: 'Dolor accusantium reiciendis recusandae natus cum ',
        price: 71,
        instructorID: 'd0cb61d7abe48b51',
        active: true,
        image: 'http://lorempixel.com/640/480/cats',
        ribbon: [Object],
        hasRibbon: false,
        id: '8377d6f5027bc885',
        instructor: 'Recursive call to GET /userinfo detected' } ]
```
As seen above, afte rthe second call, deployd gives me the error as `Recursive call to GET /userinfo detected` . I believe deployd understands recursive calls as _if same data is asked no matter from where and how, it is recursive_.

I saw in the previous answers that increasing `$limitRecursion` to the max, but I believe it won't be a permanent solution.

**Comment by rgolea** [comment] 2016-12-21 09:05
Have you tried to call it from a dpd-event? That does a one-time job. (Remember to have both dpd-event and dpd-event-extension (to enable require). The newest version of deployd does not need the last one because it has fixed this issue.
```
//courses-event
const _ = require('underscore');
$addCallback();
dpd.courses.get(query).then(data => {
   let instructors = _.chain(data).pluck('instructorId').uniq().compact().value();
   return dpd.userinfo.get({
      id: {
          $in: instructors
     }
   }).then(users => {
      let usersById = _.indexBy(users, 'id');
      return _.chain(data).map(course => {
         course.instructor = usersById[course.instructorId];
         return courses;
      })
   });
}).then(data => {
  setResult(data);
  $finishCallback();
}).catch(err => cancel(err));
```

**Comment by bahadircyildiz** [comment] 2016-12-21 09:27
But this one means using nested calls in your app and wouldn't it affect the performance? Actually, the real question is, is there really a difference between setting events in Deployd Dashboard or in your app?

**Comment by rgolea** [comment] 2016-12-21 09:41
This one means you only do 2 calls to deployd and to the database. The other way around means that you do 2 calls for each course you might have in that collection. That is, if you have 30 rows, it's 60 calls.

Secondly, I don't really know what you mean by "setting events in the app". All those events are normally written in the dashboard but it gets parsed in your resource folder. The dpd-events module however allows you to write your own api endpoint. And in that api endpoint you're just making 2 calls and doing some small operations in node. Try doing it both ways and use about 30 or 40 items in your collection and see the speed in the network request.

**Comment by rgolea** [comment] 2016-12-22 15:28
@bahadircyildiz can we close this issue?

**Comment by bahadircyildiz** [comment] 2016-12-22 15:36
@rgolea I didn't have the chance to try out your solution at the moment, yet it is OK to close right now.

**Comment by rgolea** [comment] 2016-12-22 15:40
@bahadircyildiz try it, that is the way I am using it. you'll be surprised

**Closed** 2016-12-22 15:40 UTC

**Comment by andreialecu** [comment] 2016-12-22 15:46
I can confirm that the solution posted by @rgolea is the correct one for this sort of problem.

**Comment by rgolea** [comment] 2016-12-22 16:08
@andreialecu thank you!
