### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by uniquegodwin** [deployd/deployd#814] opened 2017-05-19 08:46 UTC
I see no development for over 6 months. Is this project still active?

**Comment by NicolasRitouet** [comment] 2017-07-20 19:22
that's true that the level of contribution is quite low at the moment, it mostly depends on the community and the maintainers.
There's not much to maintain at the moment since deployd is quite stable.
But we're working on releasing a 1.0.0 (slowly but surely) where the CLI, the dashboard and the clientlib will be released as a separate npm module.
You can follow some progress here:
- https://github.com/deployd/deployd-cli
- https://github.com/deployd/dpd-dashboard

We haven't given up yet on deployd, and any help is more than welcome.

I'll make some cleanup and make it easier to contribute (the modular approach will help).

I'm closing this ticket since it's not a bug (yet!), but feel free to ask more questions about this.

**Closed by NicolasRitouet** 2017-07-20 19:22 UTC
